\documentclass{article}
\usepackage[sc]{mathpazo}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{natbib}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\usepackage{url}
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}
\hypersetup{
 pdfstartview={XYZ null null 1}}

\newcommand{\dispRity}{\texttt{dispRity} }
\newcommand{\R}{\texttt{R} }

\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
# set global chunk options
opts_chunk$set(fig.path='figure/minimal-', fig.align='center', fig.show='hold')
options(formatR.arrow=TRUE,width=90)
@


\title{\texttt{dispRity} demo for palaeobiologists}


\author{Thomas Guillerme \\ guillert@tcd.ie}

\maketitle

This demo aims to give quick overview of the \dispRity package (v.\Sexpr{packageVersion("dispRity")}) for palaeobiology analysis.
Please refer to \href{https://github.com/TGuillerme/dispRity}{GitHub page: github.com/TGuillerme/dispRity} for other vignettes, namely the \dispRity tutorial that explains the functions in more detail.

To keep it short, this package allows to easily perform \textbf{disparity-through-time} analysis.
This type of analysis often starts by ordinating \textbf{morphometric} or \textbf{cladistic} data into a multidimensional object hereafter called the \textbf{morphospace}.
One might then be interested how the occupancy of the morphospace changes through time by measuring a summary metric of this morphospace through time, called \textbf{disparity}.
In the morphospace case, disparity might be seen as a value summarising the diversity of morphologies.

This demo showcases a typical disparity-through-time analyse: we are going to test whether the disparity changed through time in this dataset since the last 100 million years.

\tableofcontents

\section{Before starting}
\subsection{Installing \dispRity}
You can install this package easily if you are using the latest version of \R and \texttt{devtools}.

<<installation, eval=FALSE>>=
install.packages("devtools")
library(devtools)
install_github("TGuillerme/dispRity", ref = "release")
library(dispRity)
@

\subsection{The morphospace}
In this example, we are going to use a subset of the data from \cite{beckancient2014} that contains an ordinated cladistic matrix and a phylogenetic tree containing both the same 50 taxa along side a table that contains some first and last occurence data for several taxa.
The ordinated matrix will represent our full morphospace, i.e. all the morphologies that ever existed through time (for this dataset).

<<data, fig.width=8, fig.height=8, out.width='.8\\linewidth'>>=
## Loading demo and the package data
library(dispRity)

## Setting the random seed for repeatability
set.seed(123)

## The morphospace:
data(BeckLee_mat50)
head(BeckLee_mat50[,1:5])

dim(BeckLee_mat50)
## The morphospace contains 50 taxa and has 48 dimensions (or axis)

## A list of first and last occurrences data for some fossils
data(BeckLee_ages)
head(BeckLee_ages)

## And a phylogeny:
data(BeckLee_tree)
plot(BeckLee_tree, cex=0.8); axisPhylo(root=140)
@ 

Note that you can have an even nicer tree if you use the \texttt{strap} package:

<<strap, eval=FALSE>>=
install.packages(strap)
library(strap)
geoscalePhylo(BeckLee_tree, cex.tip=0.8, cex.ts=0.6)
@

\section{A disparity-through-time analysis}
\subsection{Splitting the morphospace through time} 
One of the crucial steps in disparity-through-time analysis is to split the full morphospace into smaller sub-samples that contain the total amount of morphologies at certain points in time (time-slicing) or during certain periods in time (time-binning).
Basically, the full morphospace in the previous step represents the total amount of morphologies in all time and is likely to be greater than any sub-sample of the morphospace.

The \dispRity package provides a \texttt{time.series} function that allows to split the morphospace time slices (using \texttt{method="continuous"}) or into time bins (using \texttt{method="discrete"}).
In this example, we are going to split the morphospace into 5 equal time bins of 20 million years long from 100 million years ago (Mya) to the present.
Note that we can also provide here the table containing the first and last occurrences data for some fossils to take into account some fossils that might span between our different bins.

<<time-binning>>=
## Creating the vector of time bins ages
time_bins <- rev(seq(from=0, to=100, by=20))

## Splitting the morphospace using the time.series function
binned_morphospace <- time.series(data = BeckLee_mat50, tree = BeckLee_tree,
    method = "discrete", time = time_bins, inc.nodes = FALSE,
    FADLAD = BeckLee_ages)
@ 

The warning message tells us that some taxa were considered as single points in time because we didn't provide any temporal range information for some taxa.
The output object is a \dispRity object.
For details about this object class, please refer to the \href{https://github.com/TGuillerme/dispRity}{other vignettes}.
In brief however, \dispRity objects are lists of different elements (i.e. disparity results, morphospace sub-samples, etc...) that display only a summary of the object when calling the object for visualisation reasons.

<<time-binning2>>=
## The object class
class(binned_morphospace)

## What's in the object (messy version for the console!)
str(binned_morphospace)
names(binned_morphospace)

## How it's printed by default
binned_morphospace
@ 

Note that these objects will gradually contain more information when reaching higher steps in the disparity-through-time analysis.

\subsection{Bootstrapping the data}
Once we obtain our different subsamples, we might want to bootstrap or/and rarefy it (i.e. pseudo-replicating the data).
The bootstrap will allow us to make each subsample more robust to outliers and the rarefaction will allow us to compare slices with the same number of taxa to get rid of eventual sampling problems.
For that, we can use the \texttt{boot.matrix} function that allows to bootstrap the \dispRity object along with the \texttt{rarefaction} option that will rarefy it.

<<boot.rare>>=
## Bootstrapping each sub-sample 100 times
boot_bin_morphospace <- boot.matrix(binned_morphospace, bootstraps = 100)

## Getting the minimum number of rows (=taxa) in the sub-samples
min(unlist(lapply(binned_morphospace$data, nrow)))

## Bootstrapping each sub-sample 100 times and rarefying them 
rare_bin_morphospace <- boot.matrix(binned_morphospace, bootstraps = 100,
    rarefaction = 6)

## Note that the output objects are both from the "dispRity" class ...
class(boot_bin_morphospace); class(rare_bin_morphospace)

## ... and display some more information on the previous step when called
boot_bin_morphospace
rare_bin_morphospace
@ 

\subsection{Calculating disparity}

We can now calculate the disparity within each sub-sample along side with some confidence intervals generated by the pseudo-replication step above (bootstrap/rarefaction).
Disparity can be calculated in many ways and this package allows user to come up with their own disparity metrics.
For more info, please refer to the \href{https://github.com/TGuillerme/dispRity}{other vignettes}.

In this example, we are going to calculate the spread of the data in each sub-sample by calculating the disparity as the sum of the variance of each dimension of the morphospace in each sub-sample using the \dispRity function.

<<disparity>>=
## Disparity for the bootstrapped data
boot_disparity <- dispRity(boot_bin_morphospace, metric = c(sum, variances))

## Disparity for the rarefied data
rare_disparity <- dispRity(rare_bin_morphospace, metric = c(sum, variances))

## Again, these objects are both from the "dispRity" class and just display
## some information when called, note the results!
boot_disparity
rare_disparity

## To display the actual results we can use the summary function
summary(boot_disparity)
summary(rare_disparity)

## See more options on the summary function:
?summary.dispRity
@ 

\subsection{Plotting the results}
It is sometimes easier to visualise the results in a plot than in a table.
For that we can use the \texttt{plot} function to plot the \dispRity objects.

<<plot, fig.width=10, fig.height=5, out.width='1\\linewidth'>>=
## Graphical options
quartz(width = 10, height = 5) ; par(mfrow = (c(1,2)), bty = "n")

## Plotting the bootstrapped and rarefied results
plot(boot_disparity, main = "bootstrapped results")
plot(rare_disparity, main = "rarefied results")

## See more options on the plot function:
?plot.dispRity
@

As we can see in this case, the rarefaction tends to increase the confidence intervals around the mean.

\subsection{Testing differences}
Finally, to draw some conclusions from these results, we need to apply some statistical testing.
As stated before, we wanted to test whether the disparity changed through time in this dataset since the last 100 million years.
To do so, we can simply apply some comparisons of the means between each time-bins in a sequential manner to see whether the disparity in bin X is equal to the disparity in bin Y which is in turn equal to the disparity in bin Z, etc.
Because our data is temporally auto-correlated (i.e. what happens in bin Y is dependent on what happened in bin X) and was pseudo-replicated (i.e. each bootstrap draw creates non-independent sub-samples because they are all based on the same sub-sample), we are going to apply a non-parametric mean comparison: the \texttt{wilcox.test}.
Also, we are going to apply a p-value correction to avoid type I error inflation due to performing multiple test for the same hypothesis.

<<testing>>=
## testing the differences between bins in the bootstrapped dataset.
test.dispRity(boot_disparity, test = wilcox.test, comparison = "sequential",
    correction = "bonferroni")

## testing the differences between bins in the rarefied dataset.
test.dispRity(rare_disparity, test = wilcox.test, comparison = "sequential",
    correction = "bonferroni")
@ 

Here our results show significant changes in disparity through time between all time bins during the last 100 million years.
However, when looking at the rarefied results, there is no significant difference between the time bins in the Cenozoic (60-40, 40-20 and 20-0 Mya), suggesting that the differences detected in the first test might just be due to the differences in number of taxa sample (respectively \Sexpr{unlist(lapply(binned_morphospace[[1]], nrow))[[3]]}, \Sexpr{unlist(lapply(binned_morphospace[[1]], nrow))[[4]]} and \Sexpr{unlist(lapply(binned_morphospace[[1]], nrow))[[5]]} in each time bin).



\bibliographystyle{sysbio}
\bibliography{References}

\end{document}