\documentclass{article}
\usepackage[sc]{mathpazo}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{natbib}
\usepackage[utf8]{inputenc}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\usepackage{url}
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}
\hypersetup{
 pdfstartview={XYZ null null 1}}

\newcommand{\dispRity}{\texttt{dispRity} }
\newcommand{\R}{\texttt{R} }

\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
# set global chunk options
opts_chunk$set(fig.path='figure/minimal-', fig.align='center', fig.show='hold')
options(formatR.arrow=TRUE,width=90)
@


\title{\texttt{dispRity} manual}


\author{Thomas Guillerme}

\maketitle

\dispRity is a package for calculating disparity in \texttt{R}.
It allows to summarise ordinated matrices (e.g. MDS, PCA, PCO, PCoA) into single values.

\tableofcontents

\section{Before starting}
\subsection{Glossary}
Because this package is aimed to be multidisciplinary, many names or terms used in this tutorial might be non-familiar to certain fields.
Here is a list of what are the exact meaning of these term:
\begin{itemize}
\item \textbf{Ordinated space}: it designates the mathematical multidimensional object studied here. In morphometrics, this one is often referred as being the morphospace, or the cladisto-space for cladisticts or the eco-space for ecology, etc. In practice though, this term designates an ordinated matrix where the columns represent the dimensions of the ordinated space (often $>$ 3!) and the rows represent the elements within this space.
\item \textbf{Elements}: it designates the rows of the ordinated space, elements can be either taxa, field sites, countries, etc...
\item \textbf{Dimensions}: it designates the columns of the ordinated space. The dimensions can also be referred to as axis.
\item \textbf{Series}: it designates sub-samples of the ordinated space. Basically a series contain the same number of dimensions as the morphospace but might contain a smaller number of elements. For example, if our ordinated space is composed of birds and mammals (i.e. the elements) and 50 dimensions, we can create two series of just mammals or birds as elements (but the same 50 dimensions) to look at the difference in disparity between both groups.
\end{itemize}

\subsection{Installation}
You can install this package easily if you use the latest version of \R and \texttt{devtools}.

<<installation, eval=FALSE>>=
install.packages("devtools")
library(devtools)
install_github("TGuillerme/dispRity", ref = "release")
library(dispRity)
@

\noindent Note that we use the \texttt{release} branch here which is version \Sexpr{packageVersion("dispRity")}.
For the piping-hot (but potentially full of bugs) version, one can change the argument \texttt{ref = "release"} to \texttt{ref = "master"}.
This package depends mainly on the \texttt{ape} package and the \texttt{timeSliceTree::paleotree} function.

\subsection{Data}
In this tutorial we are going to use a subset of the ordinated cladistic data from \cite{beckancient2014} that contains 50 taxa ordinated using their cladistic distance (i.e. the distance between their discrete morphological characters).
Note that this data is more oriented towards palaebiology analysis but that it can apply to other disciplines.
Please refer to the \href{https://github.com/TGuillerme/dispRity}{GitHub page: github.com/TGuillerme/dispRity} for other vignettes covering some specific example of the package with ecological data.

<<data, fig.width=8, fig.height=8, out.width='.8\\linewidth'>>=
## Loading the package
library(dispRity)

## Loading the ordinated matrix containing 50 taxa
data(BeckLee_mat50)
dim(BeckLee_mat50)
head(BeckLee_mat50[,1:5])

## Loading another ordinated matrix containing 50 tips + 49 nodes
data(BeckLee_mat99)
dim(BeckLee_mat99)
head(BeckLee_mat99[,1:5], 2)
tail(BeckLee_mat99[,1:5], 2)

## Loading a list of first and last occurrence data
data(BeckLee_ages)
head(BeckLee_ages)

## Loading the phylogeny
data(BeckLee_tree)
plot(BeckLee_tree) ; nodelabels(cex=0.8) ; axisPhylo(root=140)
@ 

\subsection{A quick go through}
Here is a really crude and quick go through the package to show some of the features of this package.
Note that all these features will be discussed in more details below.

<<Quick go, fig.width=5, fig.height=5, out.width='.5\\linewidth'>>=
## Splitting the data
sliced_data <- time.series(BeckLee_mat99, BeckLee_tree, method = "continuous",
    model = "acctran", time = rev(seq(from=0, to=130, by=15)), FADLAD = BeckLee_ages)
## Bootstrapping the data
bootstrapped_data <- boot.matrix(sliced_data, 100)
## Calculating disparity
sum_of_variances <- dispRity(bootstrapped_data, metric = c(sum, variances))
## Summarising the results
summary(sum_of_variances)
plot(sum_of_variances)
## Testing some the effect of time on disparity
summary(test.dispRity(sum_of_variances, test = aov, comparisons = "all"))
@

\section{Package specificities}

\subsection{The \dispRity objects}
Disparity analysis can involve a lot of shuffling around with many matrices (especially when bootstrapping the data) which can be a bit impractical to visualise and quickly jam your \R console.
For example, we can have a look at the structure of the object created in the quick example:

<<dispRity class1, eval=FALSE>>=
str(sum_of_variances)
## That's a more than 4500 lines of output!
@

\noindent Therefore this package proposes a new class of object called \dispRity objects.
These objects allow to easily use a S3 method functions such as \texttt{summary.dispRity} (just called as \texttt{summary}; see section \ref{summary}) or \texttt{plot.dispRity} (just called as \texttt{plot}; see section \ref{plot}).
But also, this allows to use the S3 method for printing \dispRity objects via \texttt{print.dispRity} that allows to summarise the content of the objects similar to the \texttt{phylo} class objects (see \texttt{print.phylo::ape}).

<<dispRity class2>>=
## Which class is the sum_of_variances object?
class(sum_of_variances)
## What's in the object
names(sum_of_variances)
## We can summarise it using the S3 method print.dispRity
sum_of_variances
## This displays some information about what's in the object
@ 

\noindent Note however, that it is always possible to recall the full object using the argument \texttt{all=TRUE}:

<<dispRity class3, eval=FALSE>>=
## Displaying the full object
print(sum_of_variances, all=TRUE)
@ 

\noindent Finally, some utility functions such as \texttt{get.dispRity} or \texttt{extract.dispRity} allows to access to some specific content of the object:

<<dispRity class4>>=
## Extracting some specific series from the disparity object
series_1_and_4 <- get.dispRity(sum_of_variances, what=c(1,4))
series_1_and_4
## The observed disparity
extract.dispRity(sum_of_variances)
## The list of bootstrapped scores of disparity
str(extract.dispRity(sum_of_variances, observed = FALSE))
@

\subsection{Modular functions}
This package aims to be a modular package where users can personalise some aspects of the package fairly easily.
In this version \Sexpr{packageVersion("dispRity")} only one function is fully modular (\dispRity; see section \ref{disparity}) but more will be hopefully available in the near future (see section \ref{developments}).

The modular idea is that users can use implemented tools to help facilitating their own personalised function.
For example, the \dispRity function intake a \texttt{metric} argument designating how disparity should be calculated.
This argument can take some already implemented functions such as \texttt{mean} but also some completely new ones such as the sum divided by length:

<<dispRity modular>>=
## Disparity measured as the mean
summary(dispRity(sliced_data, metric = mean))
## A function for measuring the sum divided by the length (the mean!)
sum.by.length <- function(X)  sum(X)/length(X)
## Disparity measured as the mean divided by the length
summary(dispRity(sliced_data, metric = sum.by.length))
## Giving the exact same results!
@

\noindent For more information concerning this modularity, please refer to the \href{https://github.com/TGuillerme/dispRity}{GitHub page: github.com/TGuillerme/dispRity} for the vignette about the metric implementation in \dispRity.

\section{Functions}

\subsection{\texttt{tree.age}}
\subsection{\texttt{cust.series}}
\subsection{\texttt{time.series}}
\subsection{\texttt{boot.matrix}}
\subsection{\texttt{dispRity}}
\label{disparity}
\subsection{\texttt{summary}}
\label{summary}
\subsection{\texttt{plot}}
\label{plot}
\subsection{\texttt{test.dispRity}}

\section{Developments}
\label{developments}
As stated at the start of the demo, this version \Sexpr{packageVersion("dispRity")} is still in development and many parts are missing.
Here are the new functionalities that will be implemented before the proper release version (v.1).

\subsection{More user defined stuff}
I intend also develop functions to help users to develop their own algorithms for the bootstrap method (via \texttt{make.boot}) or the evolutionary models (via \texttt{make.model}).
Both functions will provide similar testing as the \texttt{make.metric} function.

\subsection{Faster!}
Finally, for long analysis, I intend to develop a parallel running version of the package.
In fact, most of the internal functions are base on \texttt{lapply} functions that can be easily passed to \texttt{snow::parLapply} or similar parallel functions.

\bibliographystyle{sysbio}
\bibliography{References}

\end{document}