\documentclass{article}
\usepackage[sc]{mathpazo}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\usepackage{url}
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}
\hypersetup{
 pdfstartview={XYZ null null 1}}

\newcommand{\dispRity}{\texttt{dispRity} }
\newcommand{\R}{\texttt{R} }

\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
# set global chunk options
opts_chunk$set(fig.path='figure/minimal-', fig.align='center', fig.show='hold')
options(formatR.arrow=TRUE,width=90)
@


\title{\texttt{dispRity} demo for palaeobiologists}


\author{Thomas Guillerme \\ guillert@tcd.ie}

\maketitle

This demo aims to give quick overview of the \dispRity package (v.\Sexpr{packageVersion("dispRity")}) for palaeobiology analysis.
Please refer to \href{https://github.com/TGuillerme/dispRity}{GitHub page: github.com/TGuillerme/dispRity} for other vignettes, namely the \dispRity tutorial that explains the functions in more details.

To keep it short, this package allows to easily perform \textbf{disparity-through-time} analysis.
This type of analysis often starts by ordinating \textbf{morphometric} or \textbf{cladistic} data into a multidimensional object hereafter called the \textbf{morphospace}.
One might then be interested how the occupancy of the morphospace changes through time by measuring a summary metric of this morphospace through time, called \textbf{disparity}.
In the morphospace case, disparity might be seen as a value summarising the diversity of morphologies.

This demo showcases a typical disparity-through-time analyse with the following steps:

\begin{enumerate}
\item Installing \dispRity
\item The morphospace
\item Splitting the morphospace through time
\item Bootstrapping the data
\item Calculating disparity
\item Plotting the results
\item Testing differences
\end{enumerate}

\section{Installing \dispRity}
You can install this package easily if you are using the latest version of \R and \texttt{devtools}.

<<installation, eval=FALSE>>=
install.packages("devtools")
library(devtools)
install_github("TGuillerme/dispRity", ref = "release")
library(dispRity)
@

\section{The morphospace}
In this example, we are going to use a subset of the data from \cite{beckancient2014} that contains an ordinated cladistic matrix and a phylogenetic tree containing both the same 50 taxa along side a table that contains some first and last occurence data for several taxa.
The ordinated matrix will represent our full morphospace, i.e. all the morphologies that ever existed through time (for this dataset).

<<data, fig.width=8, fig.height=8, out.width='.8\\linewidth'>>=
## Loading demo and the package data
library(dispRity)

## The morphospace:
data(BeckLee_mat50)
head(BeckLee_mat50[,1:5])

dim(BeckLee_mat50)
## The morphospace contains 50 taxa and has 48 dimensions (or axis)

## A list of first and last occurrences data for some fossils
data(BeckLee_ages)
head(BeckLee_ages)

## And a phylogeny:
data(BeckLee_tree)
plot(BeckLee_tree, cex=0.8); axisPhylo(root=140)
@ 

Note that you can have an even nicer tree if you use the \texttt{strap} package:

<<installation, eval=FALSE>>=
install.packages(strap)
library(strap)
geoscalePhylo(BeckLee_tree, cex.tip=0.8, cex.ts=0.6)
@

\section{Splitting the morphospace through time}

\section{Bootstrapping the data}
\section{Calculating disparity}
\section{Plotting the results}
\section{Testing differences}

\bibliographystyle{sysbio}
\bibliography{References}

\end{document}