---
title: "Example script the `dispRity` paper"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

This is the raw `R` script for running the examples present in the paper "`dispRity`: a modular `R` package for measuring disparity".

## Loading the package and the data

Loading the packages:

```{r}
## Installing (if needed) and loading devtools
if(!require(devtools)) install.packages("devtools")
library(devtools)

## Installing (if needed) and loading dispRity
if(!require(dispRity)) install_github("TGuillerme/dispRity", ref = "release")
library(devtools)
```

Loading the datasets:

```{r}
## 50*48 PCO matrix
data(BeckLee_mat50)

## 99*97 PCO matrix
data(BeckLee_mat99)

## 50 taxa tree
data(BeckLee_tree)

## FADLAD data
data(BeckLee_ages)
```

## Typical disparity among groups analysis

The wrapper version:

```{r}
## Creating the groups (crown and stem - ignoring the nodes)
mammal_groups <- crown.stem(BeckLee_tree, inc.nodes = FALSE)

## Measuring disparity as the sum of variances
disparity <- dispRity.per.group(data = BeckLee_mat50, group = mammal_groups,
                                metric = c(sum, variances))
```

The detailed version:

```{r, fig.width = 8, fig.height = 8}
## Creating custom subsets
subsets <- custom.subsets(data = BeckLee_mat50, group = mammal_groups)

## Bootstrapping the data
bootstraps <- boot.matrix(subsets)

## Measuring disparity as the sum of variance
disparity2 <- dispRity(bootstraps, metric = c(sum, variances))

## Printing the results
disparity2

## Summarising the results
summary(disparity2)

## Plotting the results
plot(disparity2)

## Testing the differences
test.dispRity(disparity2, test = wilcox.test)
```

## Typical disparity-through-time analysis

The wrapper version

```{r}
## Get the time bins
time_bins <- c(100.5, 66, 56, 33.9)

## Calculate disparity through time (sum of variances)
disparity3 <- dispRity.through.time(data = BeckLee_mat50, tree =  BeckLee_tree,
                                   time = time_bins, metric = c(sum, variances))
```

```{r, fig.width = 8, fig.height = 8}
## Creating the time subsets
time_subsets <- time.subsets(data = BeckLee_mat50, tree = BeckLee_tree,
                             time = time_bins, method = "discrete")

## Bootstrapping the data
bootstraps2 <- boot.matrix(time_subsets)

## Measuring disparity as the sum of variance
disparity4 <- dispRity(bootstraps2, metric = c(sum, variances))

## Summarising the results
summary(disparity4)

## Plotting the results
plot(disparity4, type = "continuous")

## Testing the effect if time
test.dispRity(disparity4, test = adonis.dispRity)
```


